---
- name: Converge
  hosts: all
  tasks:
    - name: Getting ssl dhparams status
      ansible.builtin.stat:
        path: /etc/ssl/dhparams.pem
        register: dhparams

    - name: Creating ssl dhparams cert
      ansible.builtin.command: openssl dhparam -out /etc/nginx/ssl-dhparams.pem 4096
      when: not dhparams.stat.exists

    - name: Configure NGINX
      ansible.builtin.include_role:
        name: ansible-role-nginx-config
      vars:
        nginx_config_debug_output: true

        nginx_config_selinux: true
        nginx_config_selinux_tcp_ports:
          - 80
          - 443

        nginx_config_upload_ssl_enable: true
        nginx_config_upload_ssl_crt:
          - src: ../common/files/ssl/molecule.crt
            dest: /etc/ssl/certs
            backup: true
        nginx_config_upload_ssl_key:
          - src: ../common/files/ssl/molecule.key
            dest: /etc/ssl/private
            backup: true

        nginx_config_main_template_enable: true
        nginx_config_main_template:
          template_file: nginx.conf.j2
          deployment_location: /etc/nginx/nginx.conf
          backup: true
          config:
            main:
              user:
                username: nginx
              worker_cpu_affinity:
                auto: true
              worker_priority: 0
              worker_processes: auto
              worker_rlimit_core: 10000
              worker_rlimit_nofile: 10000
              worker_shutdown_timeout: 30m
              error_log:
                - /var/log/nginx/ansible.log
                - file: /var/log/nginx/error.log
                  level: notice
              pid: /var/run/nginx.pid
              daemon: true
              debug_points: abort
              lock_file: /var/run/nginx.lock
              master_process: true
              thread_pool:
                - name: default
                  threads: 32
                  max_queue: 65536
                - name: molecule
                  threads: 32
              timer_resolution: 1s
              working_directory: /etc/nginx
            events:
              accept_mutex: false
              accept_mutex_delay: 500ms
              multi_accept: false
              use: epoll
              worker_aio_requests: 32
              worker_connections: 512
            http:
              include:
                - /etc/nginx/conf.d/*.conf
                - /etc/nginx/conf.d/backend/*.conf
            stream:
              include:
                - /etc/nginx/conf.d/streams/*.conf

        nginx_config_status_enable: true
        nginx_config_status_backup: true
        nginx_config_status_port: 8080
        nginx_config_status_access_log:
          path: /var/log/nginx/access.log
          format: main

        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - backup: true
            config:
              upstreams:
                - name: doh_app
                  keepalive: 32
                  least_conn: false
                  servers:
                    - address: 127.0.0.1:8453
              servers:
                - core:
                    listen:
                      - port: 80
                    server_name:
                      - '_'
                      - 'localhost'
                  log:
                    access:
                      - path: /var/log/nginx/doh-access.log
                        format: main
                    error:
                      - file: /var/log/nginx/doh-error.log
                  rewrite:
                    return:
                      code: 301
                      url: 'https://$host$request_url'
                - core:
                    max_temp_file_size: 1024m
                    client_max_body_size: 1m
                    connection_pool_size: 256
                    client_body_buffer_size: 128k
                    listen:
                      - port: "[::]:443"
                        ssl: true
                        http2: true
                      - port: "443"
                        ssl: true
                        http2: true
                    server_name:
                      - '_'
                      - 'localhost'
                  log:
                    access:
                      - path: /var/log/nginx/doh-access.log
                        format: main
                    error:
                      - file: /var/log/nginx/doh-error.log
                  ssl:
                    buffer_size: 16k
                    certificate: /etc/ssl/certs/molecule.crt
                    certificate_key: /etc/ssl/private/molecule.key
                    protocols:
                      - "TLSv1.2"
                      - "TLSv1.3"
                    prefer_server_ciphers: false
                    ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
                    dhparam: "/etc/ssl/dhparams.pem"
                  headers:
                    add_headers:
                      - name: Strict-Transport-Security
                        value: '"max-age=31536000"'
                        always: true
                  locations:
                    - location: /
                      return:
                        - 404
                    - location: /dns-query
                      grpc:
                        pass: "grpcs://doh_app"
                        socket_keepalive: On
                        connect_timeout: 10s
                        ssl_verify: false
                        ssl_protocols: TLSv1.3 TLSv1.2
                        ssl_certificate: /etc/ssl/certs/molecule.crt
                        ssl_certificate_key: /etc/ssl/private/molecule.key
