---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX is installed
      ansible.builtin.package:
        name: nginx
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Check that a page returns a status 200 and fail if the words Welcome to nginx are not in the page contents
      ansible.builtin.uri:
        url: http://localhost
        return_content: true
      register: this
      failed_when: "'Welcome to nginx' not in this.content"

    - name: Check client body cache directory exists
      ansible.builtin.stat:
        path: /var/cache/nginx/client
      check_mode: true
      register: stat_result
      failed_when: not stat_result.stat.exists

    - name: Check proxy cache directory exists
      ansible.builtin.stat:
        path: /var/cache/nginx/proxy
      check_mode: true
      register: stat_result
      failed_when: not stat_result.stat.exists

    - name: Check default.conf exists
      ansible.builtin.stat:
        path: /etc/nginx/conf.d/default.conf
      check_mode: true
      register: stat_result
      failed_when: not stat_result.stat.exists
